{% set version = "0.15.1" %}

package:
  name: pytest-flask
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-flask/pytest-flask-{{ version }}.tar.gz
  sha256: cbd8c5b9f8f1b83e9c159ac4294964807c4934317a5fba181739ac15e1b823e6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - flask
    - werkzeug >=0.7

test:
  imports:
    - pytest_flask

about:
  home: https://github.com/pytest-dev/pytest-flask
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A set of py.test fixtures to test Flask applications

  doc_url: http://pytest-flask.readthedocs.io/
  dev_url: https://github.com/pytest-dev/pytest-flask

extra:
  recipe-maintainers:
    - sodre
    - nicoddemus
