travis:
  secure:
    BINSTAR_TOKEN: bLSetTkvdCiGHhxsV2i/ZL/qbJD/Y9FkPMkxxXdOjb3tu4lvFZUcoT9Hx4EoraVz5F7wFDyyWxS5dBxTosv7U237Rh0U9duFASaCLGmD+l4qcqJja6Rtqe+FJQ55d5Ta+vkNeT5/TECAZPhC97sS00Y9tE5fS/JZQd931T6nH/chlnxrf5c6qhYXmvPO0bY5vruSCe7LUoPV6CZZArVR7TCBko3uP776TvqG70nHQTOF8Ul5Pk0MErrYYPxFbjafH2JlNtISC8Qh1zauyqpvJQqk6CQDp9wsoDmbmJ3fMrcMbwved1GwcjMzAEFpgYew2LQMaSfdEkoM9QqoLX6Ws694MgdWj4CUqYYKb5pIvrM5mibB5En3L+eColz51sEu5GtlTKguRi8LA9i8EoJEbmVhAZAyVoAplctn+MMh8iN+q/JNGJHlDZTVSYrKUAlOAAfhTQ1LEryyXQfScvw518RAi5YIFbdYfK2LXWzc09qzKzEc/6euPnAZnHX+8bffxx2nrOXTJqHNpD7WHflccFFEGsS1u4Vq8kAUGRsg30YxPG57DUW//IlPYdONTMJjbNDqev2ScbNubmtUa4KIygIHkj6mK+YdMb39ekpIT+ot50gKnUZF2kmmXJ5TsMxXlOjQehUHJdsOQVRkReYg0bBlV5w5PWlM1SI+/jMAz5E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
