travis:
  secure:
    BINSTAR_TOKEN: OyyEGS9EfNcs066NvIzxBMgJ2XDOnr0qd7jBZ41xpcopRw7/u7HbbssyVWew83hstuemy2ev4pZofUNoH5mgGSkPHDA9HhlwBce8r6CE7EEdETEL7befjoYS4XMIejiDvz1Hp6lzjGQ9x7QmoCZqC34cxE9kp23veplqCJm7rkj7AQ+/d2Cfu757qrbwRbIq7lgmRXNLWD/HUosig1RfC/kvnoG1ngyKTA5HXLjwU8LOiLInndEPg5ROt/Sk43GrI2cNhyCMfY4A7QRKbhXDkNTJel8SE9EEOkC9HMupLKbg3BzoRvThCCZ3xKs3z7xY1MIOe0/8KG3m56QpN760JzFcKb3qi2sbrkmVFXzipnEG+XBF5mzkSvPqYHF/W+Od2e/jBUwj4qZH/xVgBWm92u03vFj3bFu5kSgpEW+PqQH+hIMM8sHKpvd5xarKjvOloREc9dkmHC329FyMGSQfOlCmqcc9ZqK6egOwRm2JrfnKfEhZpBDHEbB96U1iq4uLjuhjZ33OMN6tg20plr57wcVZJaRTfHkmw38R8uFSbVZ2WQMOt/eNxY6Z+rj4QYduBE5HGRNlPQ918bsg94lBqJ4+P/0gK0xoLHWCALz94N1Yh0rLjsL/Uxrqqqc23A2aq5IleeEgWPI5pxSDryld8u8CzmfpG6taEdVIBofr9JM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
