travis:
  secure:
    BINSTAR_TOKEN: ruOnQGEk1zIJRiC9liD+YYasKZhyuhQYQqyHihIX6y5D6nmMyCYG2KSfdGw3rJ/2LwBZM2DrTEmllUgQDqaCGfz2Jv4Siqq8yrHcPerYurErECVhOuE6qZbgX1qVg3o/i16b0MvGXRxuQzzISOcfKQiVv7rvMeUeOmKx0X7ma75GEcHhnFizDehf1ulP6HzFPMvOgCCHPw0g+EwnuGYwvJSOJYAi853fk/5lJQAONcUKHz7QljKhrowH46z5qqoVHkAUn70AV/3lE5nDMap4FviV2ZQsIljreC0VqgndJsTkDrdAu8O51M62r8p9lmzhRUD0nEk8RE0uNXtEMWq3GIZgPFRQZ42XzlVmP+s2BEz88lt3K7TpM+8csvWrCv6MwmV9nNsAzsNsi2bqVpabiW4KRaeydKg1xSTaSSOEfkWbr5ObufoC13WT6cdXQ7Znv8r/goELOY0UhuaDAzk/pj/adFcBbHcPQC4bCDm69IgKSuYpClSBqnMnFceLiX647mnKnWfCfupggh/rLzR5BbvPIIkFlcj0y2NbFLFCZE4lR6jEsPV7pCNhvafSLf3Lbpbb64PUOahu5WG1C3zezBc4f6teqr8/cQeQOj3oFb3BLtqPfGgp1OjNmhh9Bav6XbpQXUQeydMI9javROTm/lNF2E09LziUhfDMMboVtOs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
